services:
  # Development environment
  docusaurus-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCUSAURUS_VERSION: "3.9.2"
    container_name: docusaurus-dev
    ports:
      - "80:80"
    volumes:
      # Mounting the local project directory
      - ./website:/app
      # Cache for node_modules (faster builds)
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run start -- --host 0.0.0.0 --port 80

  # Production environment
  docusaurus-prod:
    build:
      context: ./website
      dockerfile: ../Dockerfile.production
      args:
        DOCUSAURUS_VERSION: "3.9.2"
    container_name: docusaurus-prod
    ports:
      - "80:80"
    restart: unless-stopped
    profiles:
      - production

volumes:
  node_modules:
