# .github/workflows/deploy.yml

name: github pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'website/**'

env:
  WORKDIR: website
  CUSTOM_DOMAIN: blog.justcloud.pl

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Dump GitHub context
        working-directory: ${{ env.WORKDIR }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Dump job context
        working-directory: ${{ env.WORKDIR }}
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      
      - name: Dump steps context
        working-directory: ${{ env.WORKDIR }}
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      
      - name: Dump runner context
        working-directory: ${{ env.WORKDIR }}
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: npm ci
      
      - name: Build
        working-directory: ${{ env.WORKDIR }}
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.WORKDIR }}/build
          cname: ${{ env.CUSTOM_DOMAIN }}
          allow_empty_commit: true